defaults: &defaults
  cache_seconds: 120

feeds:
  it:
    <<: *defaults
    sources:
      - title: TechCrunch
        url: https://techcrunch.com/feed/
      - title: The Verge
        url: https://www.theverge.com/rss/index.xml
      - title: Ars Technica
        url: http://feeds.arstechnica.com/arstechnica/index/
      - title: Wired
        url: https://www.wired.com/feed/rss
      - title: ITmedia (総合)
        url: https://rss.itmedia.co.jp/rss/2.0/itmedia_all.xml
      - title: ASCII.jp (トップ)
        url: https://ascii.jp/rss.xml
      - title: ZDNet Japan
        url: http://feeds.japan.zdnet.com/zdnet/rss
      - title: CNET Japan
        url: http://feed.japan.cnet.com/rss/index.rdf
