defaults: &defaults
  cache_seconds: 120

feeds:
  japan:
    <<: *defaults
    sources:
      - title: ITmedia (総合)
        url: https://rss.itmedia.co.jp/rss/2.0/itmedia_all.xml
      - title: ZDNet Japan
        url: http://feeds.japan.zdnet.com/zdnet/rss
      - title: Gizmodo Japan
        url: https://www.gizmodo.jp/index.xml
      - title: JAPAN BUSINESS PRESS
        url: https://jbpress.ismedia.jp/feed/rss
      - title: Engadget Japanese
        url: https://japanese.engadget.com/feed/rss.xml

  world:
    <<: *defaults
    sources:
      - title: TechCrunch
        url: https://techcrunch.com/feed/
      - title: The Verge
        url: https://www.theverge.com/rss/index.xml
      - title: Ars Technica
        url: http://feeds.arstechnica.com/arstechnica/index/
      - title: Wired
        url: https://www.wired.com/feed/rss
